# Generated by Django 2.2.5 on 2019-11-17 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='subtipo',
            fields=[
                ('id_subtipo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nom_subtipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tamano',
            fields=[
                ('id_tamano', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nom_tamano', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='toppings',
            fields=[
                ('id_topping', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('topp_nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name='ordenes',
            old_name='id',
            new_name='id_dueno',
        ),
        migrations.CreateModel(
            name='prod_tam_sub',
            fields=[
                ('id_pts', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_productoPts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_productoPts', to='orders.producto')),
                ('id_subtipoPts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_subtipoPts', to='orders.subtipo')),
                ('id_tamanoPts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_tamanoPts', to='orders.tamano')),
            ],
        ),
        migrations.CreateModel(
            name='prod_orden',
            fields=[
                ('id_prod_creado', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_ordenIn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_ordenIn', to='orders.ordenes')),
                ('id_ptsWho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_ptsWho', to='orders.prod_tam_sub')),
                ('topping', models.ManyToManyField(blank=True, related_name='prod_topping', to='orders.toppings')),
            ],
        ),
        migrations.CreateModel(
            name='pizza',
            fields=[
                ('id_pizza',models.AutoField(primary_key=True,auto_created=True,serialize=True)),
                ('num_toppings', models.IntegerField()),
                ('id_subtipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_subtipoPizza', to='orders.subtipo')),
            ],
        ),
    ]


# 21 | orders       | 0002_auto_20191117_2024                  | 2019-11-17 15:24:32.44005-05


