# Generated by Django 2.2.5 on 2019-11-18 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191118_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_tam_sub',
            name='id_tamanoPts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_tamanoPts', to='orders.tamano'),
        ),
    ]
