# Generated by Django 2.2.7 on 2020-01-02 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191118_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_tam_sub',
            name='id_subtipoPtsPizza',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='id_subtipoPtsPizza', to='orders.pizza'),
            preserve_default='true',
        ),
    ]
