# Generated by Django 2.2.7 on 2020-01-02 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_prod_tam_sub_id_subtipoptspizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_tam_sub',
            name='id_subtipoPtsPizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_subtipoPtsPizza', to='orders.pizza'),
        ),
    ]
