# Generated by Django 2.2.5 on 2020-01-04 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200102_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod_orden',
            name='topping',
        ),
    ]
