# Generated by Django 2.2.5 on 2020-01-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_prod_orden_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_orden',
            name='toppings',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
