# Generated by Django 2.2.5 on 2020-01-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_carritocompras'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritocompras',
            name='fecha_prod_car',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
