# Generated by Django 2.2.5 on 2020-01-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200105_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_orden',
            name='toppings',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
