# Generated by Django 2.2.5 on 2020-01-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200105_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompras',
            name='precio_prod_car',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
